version: '3'

services:

  db:
    image: postgres:10
    env_file: db.env
    restart: always

  billiards__score:
    depends_on:
      - db
    build: .
    image: billiards__score
    env_file:
      - db.env
    environment:
      POSTGRES_HOST: db
      DOMAINS: ''
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./data:/data